name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('test_requirements.txt') }}
      - if: github.repository == 'tillahoffmann/template'
        name: "Maybe apply template"
        run: |
          python apply_template.py myproject -u myuser -r myrepo
          ! grep --exclude-dir=.git -r TEMPLATE_NAME .
          ! grep --exclude-dir=.git -r TEMPLATE_USER .
          ! grep --exclude-dir=.git -r TEMPLATE_REPO .
          ! find . -name TEMPLATE_NAME
          ! find . -name TEMPLATE_USER
          ! find . -name TEMPLATE_REPO
      - name: "Install dependencies"
        run: "pip install -r test_requirements.txt"
      - name: "Build the project"
        run: "make build"
        env:
          # Our tests may contain a number of stochastic elements. Setting a seed will make sure
          # they're not flaky (but also hide potential issues).
          SEED: "0"
